import './globals.css'
import { VT323 } from 'next/font/google'

export const metadata = {
  title: 'NEW Wyvernhole',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
